name: Notificação de Sábado (Véspera de Domingo)

on:
  schedule:
    # 00:12 UTC de Domingo = 21:12 Horário de Brasília no Sábado 
    - cron: '12 0 * * 0'
  workflow_dispatch: # Permite rodar manualmente no botão para testes

jobs:
  enviar_vespera:
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests pytz

      - name: Rodar Script em Modo Véspera
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MODO_VESPERA: 'true'
        run: python main.py
